### ISSUE TITLE
Solving linear equation systems, e.g. stiff integrators

### ISSUE THREAD

**Issue by MartinOtter** [baggepinnen/MonteCarloMeasurements.jl#118]
It seems that there is a fundamental problem with MonteCarloMeasurements.jl when solving linear equation systems:

The linear equation system has to be build up and then solved. It seems not possible to "vectorize" these operations, so the basic operation mode of MonteCarloMeasurements fails. One could pack the construction and solution of the linear equation in a function and then use "register_primitive(yourfunc)", when I understand this correctly?

I wonder how this is done in DifferentialEquations.jl, because this problem is present for every stiff integrator (@ChrisRackauckas)

**Comment by ChrisRackauckas** [comment]
It should be hitting the generic fallbacks and not vectorize right now. RecursiveFactorization.jl would shuttle it to the generic linear algebra call. At least, I haven't checked and that's my guess. But with such a heavy function call per op, I don't think BLAS tools would help and flat loops are probably the best option anyways.

**Comment by MartinOtter** [comment]
Here is a test model

```
module TestMonteCarlo

using MonteCarloMeasurements
using LinearAlgebra

v1 = 2.0 ± 0.1
v2 = 3.0 ± 0.1 

A = [v1 v2; 2*v1 3*v2]
b = [4*v2, v1]

x1 = A\b

@show A
@show x1

A2 = copy(A)
x2 = copy(b)

luA = lu!(A2)
ldiv!(luA, x2)
@show x2
                    
end
```

resulting in the output

```
A = MonteCarloMeasurements.Particles{Float64, 2000}[2.0 ± 0.1 3.0 ± 0.1; 4.0 ± 0.2 9.0 ± 0.3]
x1 = MonteCarloMeasurements.Particles{Float64, 2000}[17.0 ± 1.1, -7.33 ± 0.04]
x2 = MonteCarloMeasurements.Particles{Float64, 2000}[17.0 ± 1.1, -7.33 ± 0.04]
```

I do not really understand how this can work, but looks fine.

The drawback is obviously, that the intermediately constructed A-matrix consumes memory of 2000 Float64 A-matrices. If a standard Monte Carlo Simulation would be used, then the storage for the A-matrix would be only present once. 

In my code, I use the "lu!(..) and "ldiv!(..)" construction and got an error with MonteCarloMeasurements. I though the issue is the solution of the linear equation system, but it seems to be something else.

**Comment by baggepinnen** [comment]
As Chris is saying, there is most likely no benefit to be had in terms of performance from using MCM here. This boils down to the struct-of-arrays vs. array-of-structs dilemma, and the data layout of MCM is the wrong one for this problem. The reason your example works is because there are some definitions for `\` on particle arrays
https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/2122b4cfc71c3a0b850c4b60cbd8ab18a070b9e1/src/MonteCarloMeasurements.jl#L152

I would guess the best way to solve stiff systems is to do the data layout permutation before solving and repackage the problem as an `EnsembleProblem` and use threads on it.

Long term, I'd like to have a type that stores arrays of particles as a matrix rather than a vector of vectors. This is already possible for static particles through `reinterpret`, but not for standard particles. With this approach, data permutation would become straightforward. I don't have any bandwidth to allocate to this at the moment though, so that's for another time. 

When static particles are used, we already use blas for a lot of operations through `reinterpret`
https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/2122b4cfc71c3a0b850c4b60cbd8ab18a070b9e1/src/particles.jl#L595

**Comment by MartinOtter** [comment]
Thanks for your explanations.
