### ISSUE TITLE
register_primitive causes "eval into closed module" warnings

### ISSUE THREAD

**Issue by cscherrer** [baggepinnen/MonteCarloMeasurements.jl#29]
My library needs this line in order for things to work properly:
```julia
foreach(register_primitive, [<=, >=, <, >])
```
But this makes `using Soss` spit out lots of warnings like this:

```julia
WARNING: eval into closed module MonteCarloMeasurements:
Expr(:function, Expr(:call, Expr(:., Base, :(:>)), Expr(:::, :p, :StaticParticles)), Expr(:block, #= Symbol("/home/chad/.julia/packages/MonteCarloMeasurements/nd0Nh/src/register_primitive.jl"):37 =#, Expr(:call, :StaticParticles, Expr(:call, :map, Expr(:., Base, :(:>)), Expr(:., :p, :(:particles))))))
  ** incremental compilation may be fatally broken for this module **
```

Should I be calling `register_primitive` differently? Do you know a way around this?

**Comment by baggepinnen** [comment]
Hmm, that might be due to the world-age being frozen after module compilation, and you using `register_primitive` from within another module. I have never tried that before and am unfortunately unfamiliar with the problem. I would suggest you try to simply copy the definitions of `register_primitive` into your library and call those functions instead and see if that solves the problem. Then you could also perhaps customize them to your particular need. In the meantime, I'll see if I can understand the problem and come up with a solution, but it might take me a couple of days.

**Comment by cscherrer** [comment]
Oh good idea, I'll try that. Let's leave this open if you don't mind, until there's a longer-term solution

**Comment by baggepinnen** [comment]
I am struggling to reproduce the error. The following code seems to work just fine without warnings. It probably just appears when another package, which is being precompiled, calls `register_primitive`.
```julia
module Temp
    using MonteCarloMeasurements
    MonteCarloMeasurements.register_primitive(<)
    __precompile__(true)
end

using MonteCarloMeasurements
p = Particles(100)
(1 < p).particles
using Main.Temp
```

**Comment by cscherrer** [comment]
I get the warnings when I activate this packages environment and the try `using` it:
https://github.com/cscherrer/RegisterPrimitiveTests

**Comment by baggepinnen** [comment]
Ok, I solved it by allowing modules to send in their own `eval` function. Your test-repo precompiles well if it looks like this
```julia
module RegisterPrimitiveTests

using MonteCarloMeasurements
MonteCarloMeasurements.register_primitive(<, eval)

end # module
```
