### ISSUE TITLE
Computing tail probabilities

### ISSUE THREAD

**Issue by arbenede** [baggepinnen/MonteCarloMeasurements.jl#67]
I'm wondering if there is a way to compute tail probabilities from a Particles variable without converting them to a vector. Say that p(x) is the (empirical) probability density associated with a Particles P, I would like to compute for example \integral_{-\infty} ^b p(x) dx = Prob(P < b)
Maybe one could redefine 
```
P < b 
```
to do that?

**Comment by baggepinnen** [comment]
The handling of comparison operators is very tricky in general. These operators can not be defined like this by default since `<` normally always returns a boolean. A user sending particles into a function might thus get the cryptic error message "non-boolean used in boolean context" if particles are used in an if statement.

What you can do is to define those operators as primitives by calling
```julia
register_primitive.([<,>,<=,>=])
mean(P<b) # your desired probability
```
with the understanding that you will get worse error messages when using particles in general functions. 

A more general solution would be to simply define a macro that calculates what you want, e.g., 
```julia
@prob P < b
```

Example:
```julia
using MacroTools, MonteCarloMeasurements
macro prob(ex)
    if @capture(ex, a_ < b_)
        op = <
    elseif @capture(ex, a_ <= b_)
        op = <=
    elseif @capture(ex, a_ > b_)
        op = >
    elseif @capture(ex, a_ >= b_)
        op = >=
    else
        error("Expected an expression on any of the forms `a < b, a > b, a <= b, a >= b`")
    end
    quote
        mean($op.(MonteCarloMeasurements.maybe_particles($(esc(a))), MonteCarloMeasurements.maybe_particles($(esc(b)))))
    end
end

julia> p = Particles()
Part10000(4.974e-18 ± 1.0)

julia> mean(p.particles .< 1)
0.8413

julia> @prob p < 1
0.8413
```
If you would like to see this macro implemented in the package, I can add it.

**Comment by baggepinnen** [comment]
Simpler implementation:
```julia
using MonteCarloMeasurements
macro prob(ex)
    ex.head == :call && ex.args[1] ∈ (:<,:>,:<=,:>=) || error("Expected an expression on any of the forms `a < b, a > b, a <= b, a >= b`")
    op = ex.args[1]
    a  = ex.args[2]
    b  = ex.args[3]
    quote
        mean($op.(MonteCarloMeasurements.maybe_particles($(esc(a))), MonteCarloMeasurements.maybe_particles($(esc(b)))))
    end
end
```

**Comment by baggepinnen** [comment]
The macro `@prob` is now available in a released version
