### ISSUE TITLE
bymap does not support function with 2 output values

### ISSUE THREAD

**Issue by arbenede** [baggepinnen/MonteCarloMeasurements.jl#74]
I have a function that takes two inputs, a numeric array and an array of Particles, that I call using bymap:

``
ret = @bymap decode(v,Y)
X = ret[1]
a = ret[2]
``
When I added the second (non-Particle) output value I got this error:
```
Output with dimension >2 is currently not supported by `bymap`.
```
Is there any workaround?

**Comment by baggepinnen** [comment]
The ideal way of handling complicated functions is to register the innermost component that fails as a primitive.

If that does not work, `@bymap` is one alternative, but I have not figured out a general way of supporting many kinds of output. A workaround would be easy though, the implementation is [here](https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/3b17227e6a72abe3822d3eeddfe5835f3dcd0136/src/bymap.jl#L54), the line ` PTNT = PT{eltype(eltype(individuals)),N}` would have to be modified to extract the eltype when an individual is a tuple instead of a number, and then an appropriate constructor call chosen to construct the particles using one of the cases in the if-else ladder below. 

You may also try the `Workspace`approach detailed [here](https://baggepinnen.github.io/MonteCarloMeasurements.jl/stable/overloading/#Difficult-cases-1).

What's the reason your function fails for particles? Maybe I can spot a simpler solution.

**Comment by arbenede** [comment]
@baggepinnen thanks once again for your prompt answer. The reason the functions fails for Particles is that during the computation an intermediate vector of Particles has to be sorted. Here is a MWE:

```
function MWE(v::Array{Int64,1},y::AbstractArray{T,1}) where T<:Number

a = convert(Vector{Int},ceil.(y) .+4)
n = length(y)

α = 1 - dot(v,y) / dot(v,v)
Phi = zeros(T,Int(sum(ceil.(y .- 1/2 .+ v*α))),2)

iP=0
for i=1:n
    nmax=floor(y[i]-1/2)
    for j=0:nmax
        x = j+1/2-y[i]
        Phi[iP+1,:] = [x,i]
        iP=iP+1
    end
end

idx = sortperm(Phi[:,1])
Phi = Phi[idx,:]

Phi, a

end
```
giving the error

```
N = 3
v = [2, 10, 15]
Y = [Particles(100,Normal(2n,n/2)) for n = 1:N]
ret = MWE(v,Y)

Comparison of uncertain values using comparison mode safe failed. Comparison operators are not
well defined for uncertain values. Call `unsafe_comparisons(true)` to enable comparison operators for
particles using the current reduction function mean. Change this function using
`set_comparison_function(f)`. For safety reasons, the default safe comparison function is maximally
conservative and tests if the extreme values of the distributions fulfil the comparison operator.
```
By the way I realized that the second output of this function is also a set of Particles of type Int. Since I need to relate these particles to input Particles in y, a new question arises: is there any guarantee that the ordering between the elements of a and the elements of y is maintened? In other words, is a[n] generated by y[n]?

**Comment by baggepinnen** [comment]
Here's how I would solve it
```julia
using MonteCarloMeasurements
function MWE(v::Array{Int64,1},y::AbstractArray{T,1}) where T<:Number

    a = convert(Vector{Int},ceil.(y) .+4)
    n = length(y)

    α = 1 - dot(v,y) / dot(v,v)
    Phi = zeros(T,Int(sum(ceil.(y .- 1/2 .+ v*α))),2)

    iP=0
    for i=1:n
        nmax=floor(y[i]-1/2)
        for j=0:nmax
            x = j+1/2-y[i]
            Phi[iP+1,:] = [x,i]
            iP=iP+1
        end
    end

    Phi = sortpart(Phi)

    Phi, a

end

function sortpart(Phi)
    idx = sortperm(Phi[:,1])
    Phi[idx,:]
end

sortpart(Phi::Array{<:AbstractParticles}) = ℝⁿ2ℝⁿ_function(sortpart, Phi)


N = 3
v = [2, 10, 15]
Y = [Particles(100,Normal(2n,n/2)) for n = 1:N]


julia> ret = MWE(v,Y)
(Particles{Float64,100}[-5.65 ± 1.3 2.88 ± 0.33; -4.78 ± 1.2 2.73 ± 0.45; … ; 0.187 ± 0.41 0.8 ± 1.2; 0.556 ± 0.72 1.5 ± 1.3], [6, 8, 10])

```
The approach is to
1. Define an inner function that contains the troublesome part
2. Make use of the helper function `ℝⁿ2ℝⁿ_function` to propagate particles through the difficult part.

Hoe this solves the problem :)

**Comment by baggepinnen** [comment]
Looking closer at this, your function does not appear to have a deterministic output size? The line
`Phi = zeros(T,Int(sum(ceil.(y .- 1/2 .+ v*α))),2)` creates a matrix where the size depends on the input values. This would have produced different results had you ran the function several times without particles compared to what it will do with particles. With particles, it will produce a matrix that is large enough to accommodate all possible scenarios (up to monte carlo error).

**Comment by arbenede** [comment]
The function that I posted is just a minimal working example to reproduce the error that I get in the true function that I am debugging. I tried the approach that you suggested using ℝⁿ2ℝⁿ_function(), and while it works in the MWE function it does not in the true function. The reason is that sorting the Particles vector is not enough, I also need the permutation vector for other computations but I could not find a way to pass it from sortpart() back to the calling function. Anyway, I solved the problem simply by writing an additional function and refactoring the code. Thanks  one more time for your help!

**Comment by baggepinnen** [comment]
Great! 😃
Make sure to carefully consider how general "non differentiable" operations interact with the Monte Carlo sampling. It's always be possible to propagate uncertainty from input to output using Monte Carlo sampling, but if intermediate quantities may vary in size or dimension, the approach taken in this package may fail.
Furthermore, if the function uncertainty is propagated through calls any function for which particles behave as a distribution rather than a number, results may differ. An example is the mean function, which is defined for both scalars and particles, but behaves differently if run on several different scalars compared to if it's called once on particles.

**Comment by arbenede** [comment]
I'm reopening the issue just to get some clarification about your last comment. When you say that if quantities vary in size or dimension the approach takes in this package may fail, do you refer to the systematic resampling? I am using this package to compute the Mean Square Error and probability of detection (thanks for adding @prob!) curves of a signal processing estimation algorithm for different level of SNR and other parameters. This algorithm does things like sorting vectors whose elements are functions of Particles, computes eigenvalues of matrices also functions of Particles, etc. Would the computed MSE only have larger Monte Carlo variance, or also some bias? Of course I can live with higher variance since I can just increase the number of Particles, but bias would be a problem. Also, is there a way to disable systematic sampling?

**Comment by baggepinnen** [comment]
With a variable varying in size, I mean something like the following
```julia
function f(p::Particles)
  1:ceil(Int, maximum(p))
end
```
The length of the returned vector depends on the value of the input argument, not on it's type.  If this is intentional and its effects considered, it's not a problem. It could be a problem if the code is not written with MCM in mind, but still has such properties.

Systematic sampling should not interact with this problem. It can be turned off in the constructor 
```julia
Particles(N, d::Distribution, systematic=false)
```
but this is not recommended. Even though the distribution is sampled systematically, we shuffle the samples (by default, this can also be turned off) so that they should be internally uncorrelated.

In your application, there are two *potentially* problematic operations.
- Sorting: this operation is not differentiable when two indices change. For differentiation with an infinitely small epsilon, this is mostly a non-issue since it is differentiable "almost everywhere". When the epsilon is large, i.e., the distribution is wide, it *might* become a problem, it all depends on how the result is used. The result can safely be used for stuff like calculating the distribution of the rank, or the probability that one element is larger than another etc. It can not as easily be used for things like "the index of the largest value is `i`", since it does not always make sense to average indices.
- Eigenvalues: This is very much related to the last point: eigenvalues are returned sorted. When two eigenvalues cross each other (they become equal), this function is non-differentiable. This is okay for saying things like "the magnitude of the largest eigenvalue is X", but may **not** be okay for things like "the eigenvector corresponding to the largest eigenvalue is V".  If eigenvalues are well separated, the second statement is not problematic, but if the two largest eigenvalues are of roughly equal size, they may both appear largest for about half of the particles. The particles representing the eigenvector of the largest eigenvalue will then contain both of the two largest eigenvectors, i.e., half of the particles will correspond to one eigenvector and the other half to the other. This is likely not what you want. All the information you need to tear the eigenvectors apart and do the right thing is there, represented in the particles, but calculating `mean.(v)` of the eigenvector will be misleading since it will not point along any of the eigenvecetors, but rather inbetween them.

**Comment by baggepinnen** [comment]
I can mention that these problems only arise when
- The resulting particles live on a non-euclidean manifold
- particles are somehow reduced to a single number 
Both of the conditions above need to be fulfilled for this to be a problem. On non-euclidean manifolds the arithmetic mean does not make sense. Consider, for instance, two locations on earth, their average lies inside the earth, whereas the average we probably would like lies on the earth's surface, the *barycenter* of the points under a certain metric. While each particle may itself be on the surface of the earth, the `mean` particle is not.
Eigenvalues, eigenvectors and permutation vectors are all stuff that are not really euclidean in nature and thus require some consideration **if** they are somehow averaged.

**Comment by baggepinnen** [comment]
I'll close this issue, but feel free to comment more if anything is unclear.
