### ISSUE TITLE
Feature Request: Nominal values

### ISSUE THREAD

**Issue by jonniedie** [baggepinnen/MonteCarloMeasurements.jl#98]
It would be cool if there was a way to keep track of nominal values too, because the mean often has different properties than the nominal run (for example, undamped oscillation with uncertainty in the frequency will look like damped oscillation if you take the mean). I’m currently doing this with a local package that redefines `\pm` and `..` to put a nominal run in the first particle, but I’m not sure if there are unintended consequences for doing it that way. I know the statistics will be slightly off, but one run out of 2001 seemed fine enough that it wasn’t worth pirating the statistics functions to only look at the dispersed runs.

If no one else has any need for this, I’m fine with just doing it the way I’ve been doing it, but I thought I’d put the feature request up just in case it’s useful for other people too.

**Comment by baggepinnen** [comment]
I was contemplating adding something like this at one point but decided against it. The problem for me was that if I have committed to propagating a distribution through a function due to the input being uncertain, then I should no longer allow myself to look at the nominal value as it will give me a false sense of the result. The problem you describe with the undamped response is a perfect example, if you visualize all the individual trajectories of the response, you'll see that they are all undamped, the nominal one just being one of many. Any form of summarization of the trajectory will result in garbage though since the phase after a while is completely stochastic. The nominal trajectory in this case represents a "typical trajectory", but it no more accurate than any of the other 2000 trajectories. In the [paper](https://arxiv.org/abs/2001.07625) I use exactly this example to illustrate how linear uncertainty propagation is a bad choice for propagating uncertainties through highly non-linear functions (figure 2). 

If you still wish to keep a nominal sample in the collection of samples, I would consider sampling the particles like normal, and then changing the particle that is closest to the nominal one. That way you would have a minimal impact on the sampled distribution.

**Comment by jonniedie** [comment]
For launch vehicles, we typically have requirements on both the nominal run and the dispersed runs. [Here is a good example](https://ntrs.nasa.gov/api/citations/20100035660/downloads/20100035660.pdf) of what our requirements generally look like. The relevant parts are O1-O7 on p. 10, and the Nichols plots in Figure 10, although these are a little bit unusual because Ares1 was a pretty unique vehicle. So for us at least, it's meaningful to propagate a true nominal run alongside the dispersed runs. MATLAB's `ureal` works similarly.

I do like the idea of having some sample trajectories in the standard visualization. I feel like that would strike a good balance between seeing the qualitative behaviors of individual runs and the quantitative statistical behavior of the group.

**Comment by baggepinnen** [comment]
I see, would a function that takes a vector of `Particles` and a vector with the nominal value and perturbs the particles such that the first particle corresponds to the nominal value be a good solution? There is already an internal function that takes an object with `Particles` fields and replaces the particles using a user-specified function, that could be wrapped to get a `nominal_object` function that extracts the nominal value.

**Comment by jonniedie** [comment]
Maybe this is what you're saying, but what I'm thinking is something like this (there would have to be more methods for specifying number of particles, etc.)

```julia
julia> function with_nominal(distribution::Distribution; nominal=mean(distribution), kwargs...)
           p = Particles(MCM.DEFAULT_NUM_PARTICLES+1, distribution; kwargs...)
           p.particles[1] = nominal
           return p
       end

julia> nominal(x::Particles) = x.particles[1];

julia> nominal_object(P) = MCM.replace_particles(P, P->P isa AbstractParticles, P->nominal(P));

julia> a = with_nominal(Uniform(3, 6), nominal=4, systematic=false)
Particles{Float64,2001}
 4.49101 ± 0.857

julia> b = with_nominal(Normal(5,1))
Particles{Float64,2001}
 5.00075 ± 0.999

julia> nominal(a+b)
9.0
```

**Comment by jonniedie** [comment]
But maybe this would all be handled better with a wrapper around regular `Particles`. I tried doing this, but it ended up being a lot of work to keep from having method ambiguities, so I just went back to making the first particle the nominal.

**Comment by baggepinnen** [comment]
@jonniedie I added some support for nominal values in https://github.com/baggepinnen/MonteCarloMeasurements.jl/blob/master/src/nominal.jl. I avoided trying to replicate all constructors by simply having a function that takes already sampled particles and inserts a nominal value. Hope it satisfies your needs :)

**Comment by jonniedie** [comment]
That's perfect, thank you!
